name: ai_containment
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - django=4.2
  - channels
  - daphne
  - requests
  - python-dotenv
  - scikit-learn
  - joblib
  - datasets
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - pip
  - pip:
      - sentence-transformers
