# Generated by Django 4.2.25 on 2026-02-23 15:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('input_hash', models.CharField(blank=True, max_length=64)),
                ('user_prompt', models.TextField()),
                ('ai_response_raw', models.TextField(blank=True, help_text='Unfiltered AI output')),
                ('ai_response_filtered', models.TextField(blank=True, help_text='Redacted output shown to user')),
                ('model_backend', models.CharField(blank=True, max_length=64)),
                ('model_name', models.CharField(blank=True, max_length=128)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('is_threat', models.BooleanField(default=False)),
                ('threat_level', models.CharField(choices=[('SAFE', '✅ Safe'), ('LOW', '🟡 Low'), ('MEDIUM', '🟠 Medium'), ('HIGH', '🔴 High'), ('CRITICAL', '💀 Critical')], default='SAFE', max_length=16)),
                ('overall_score', models.FloatField(default=0.0)),
                ('analysis_time_ms', models.FloatField(default=0.0)),
                ('input_is_threat', models.BooleanField(default=False)),
                ('input_threat_level', models.CharField(choices=[('SAFE', '✅ Safe'), ('LOW', '🟡 Low'), ('MEDIUM', '🟠 Medium'), ('HIGH', '🔴 High'), ('CRITICAL', '💀 Critical')], default='SAFE', max_length=16)),
                ('kill_switch_triggered', models.BooleanField(default=False)),
                ('blocked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Interaction Log',
                'verbose_name_plural': 'Interaction Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SecurityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('category', models.CharField(choices=[('MALICIOUS_CODE', 'Malicious Code'), ('DATA_EXFILTRATION', 'Data Exfiltration'), ('WEAPONS', 'Weapons'), ('NETWORK_ACCESS', 'Network Access'), ('PROMPT_INJECTION', 'Prompt Injection'), ('POLICY_VIOLATION', 'Policy Violation')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('severity', models.CharField(default='MEDIUM', max_length=16)),
                ('auto_kill', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Security Policies',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ThreatDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('INPUT', 'User → AI'), ('OUTPUT', 'AI → User')], max_length=8)),
                ('category', models.CharField(choices=[('MALICIOUS_CODE', 'Malicious Code'), ('DATA_EXFILTRATION', 'Data Exfiltration'), ('WEAPONS', 'Weapons'), ('NETWORK_ACCESS', 'Network Access'), ('PROMPT_INJECTION', 'Prompt Injection'), ('POLICY_VIOLATION', 'Policy Violation')], max_length=32)),
                ('severity', models.CharField(max_length=16)),
                ('confidence', models.FloatField()),
                ('semantic_score', models.FloatField(default=0.0)),
                ('matched_keywords', models.JSONField(default=list)),
                ('matched_patterns', models.JSONField(default=list)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threat_details', to='sentinel.interactionlog')),
            ],
            options={
                'ordering': ['-confidence'],
            },
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('DANGER', 'Danger'), ('CRITICAL', 'Critical')], max_length=16)),
                ('title', models.CharField(max_length=128)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sentinel.interactionlog')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='KillSwitchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('TRIGGERED', 'Triggered'), ('RESET', 'Reset')], max_length=16)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('triggered_by', models.CharField(max_length=64)),
                ('reason', models.TextField()),
                ('kill_token', models.CharField(blank=True, max_length=128)),
                ('interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sentinel.interactionlog')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
